---
title: "Apply Operation To Column"
description: "How to copy rows from one table to another in an SQL database."
tags: postgresql: basics
URL: https://github.com/ActiveState/code
Creator: 
Meta: 

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Apply Operation To Column
        </h1>
        <p>How to copy rows from one table to another in an SQL database.</p>
    	</div>
		</div>

 <div style="height:40px">
<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
Example
</span>
</div>
</div>

## Create Table Of Adventurers

```sql
-- Create table called adventurers
CREATE TABLE adventurers (
    -- string variable
    name varchar(255),
    -- integer variable
    age int,
    -- string variable
    race varchar(255)
)
```

## Insert Rows

```sql
-- Insert into the table adventurers
INSERT INTO adventurers (name, age, race)
VALUES ('Fjoak Doom-Wife', 28, 'Human'),
       ('Alooneric Cortte', 29, 'Elf'),
       ('Piperel Ramsay', 35, 'Elf'),
       ('Casimir Yardley', 14, 'Elf')
```

## Apply Operation To Column

```sql
-- Update the age column, multiplying all age values by 10
UPDATE adventurers SET age = age * 10
```

## Apply Operation To Column With Conditions

```sql
-- Update the name column where the race column is 'Elf'
UPDATE adventurers SET name = 'Some Elf'
WHERE race = 'Elf'
```

## View Table

```sql
-- Retrieve data
SELECT * FROM adventurers
```
<table border="1" style="border-collapse:collapse">
<tr><th>name</th><th>age</th><th>race</th></tr>
<tr><td>Fjoak Doom-Wife</td><td>280</td><td>Human</td></tr>
<tr><td>Some Elf</td><td>290</td><td>Elf</td></tr>
<tr><td>Some Elf</td><td>350</td><td>Elf</td></tr>
<tr><td>Some Elf</td><td>140</td><td>Elf</td></tr></table>