---
title: "Calculate Time Duration"
description: "How to calculate time duration in an SQL database."
tags: postgresql, dates
URL: https://github.com/ActiveState/code
Creator: 
Meta: 

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Calculate Time Duration
        </h1>
        <p>How to calculate time duration in an SQL database.</p>
    	</div>
		</div>

 <div style="height:40px">
<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
Example
</span>
</div>
</div>

## Create Table

```sql
-- Create table called dead_adventurers
CREATE TABLE dead_adventurers (
    -- string variable
    name varchar(255),
    -- string variable
    race varchar(255),
    -- string variable
    weapon varchar(255),
    -- date variable
    started_adventure date,
    -- date variable
    died date
)
```

## Insert Rows

```sql
-- Insert into the table dead_adventurers
INSERT INTO dead_adventurers (name, race, weapon, started_adventure, died)
VALUES ('Fjoak Doom-Wife', 'Human', 'Axe', '09-JAN-2017', '10-Nov-2017'),
       ('Alooneric Cortte', 'Elf', 'Bow', '10-JAN-2017', '11-JAN-2017'),
       ('Piperel Ramsay', 'Elf', 'Sword', '11-JAN-2017', '12-APR-2017'),
       ('Casimir Yardley', 'Elf', 'Magic', '23-JAN-2017', '06-MAY-2017')
```

## Calculate Duration Between Two Date Values

```sql
-- Get all the columns, and add a new column called days_on_adventure
-- that is the number of days between the start of the adventurer and when they died
SELECT *, died - started_adventure AS days_on_adventure FROM dead_adventurers
```
<table border="1" style="border-collapse:collapse">
<tr><th>name</th><th>race</th><th>weapon</th><th>started_adventure</th><th>died</th><th>days_on_adventure</th></tr>
<tr><td>Fjoak Doom-Wife</td><td>Human</td><td>Axe</td><td>2017-01-09</td><td>2017-11-10</td><td>305</td></tr>
<tr><td>Alooneric Cortte</td><td>Elf</td><td>Bow</td><td>2017-01-10</td><td>2017-01-11</td><td>1</td></tr>
<tr><td>Piperel Ramsay</td><td>Elf</td><td>Sword</td><td>2017-01-11</td><td>2017-04-12</td><td>91</td></tr>
<tr><td>Casimir Yardley</td><td>Elf</td><td>Magic</td><td>2017-01-23</td><td>2017-05-06</td><td>103</td></tr></table>