---
title: "Concatenate Multiple Table"
description: "How to concatenate multiple tables in an SQL database."
tags: postgresql, merging_and_joining
URL: https://github.com/ActiveState/code
Creator: 
Meta: 

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Concatenate Multiple Table
        </h1>
        <p>How to concatenate multiple tables in an SQL database.</p>
    	</div>
		</div>

 <div style="height:40px">
<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
Example
</span>
</div>
</div>

## Create Table Of Elves

```sql
-- Create table called elves
CREATE TABLE elves (
    -- string variable
    name varchar(255),
    -- integer variable
    age int,
    -- string variable
    race varchar(255),
    -- string variable
    weapon varchar(255)
)
```

## Create Table Of Dwarves

```sql
-- Create table called dwarves
CREATE TABLE dwarves (
    -- string variable
    name varchar(255),
    -- integer variable
    age int,
    -- string variable
    race varchar(255),
    -- string variable
    weapon varchar(255)
)
```

## Create Table Of Orcs

```sql
-- Create table called orcs
CREATE TABLE orcs (
    -- string variable
    name varchar(255),
    -- integer variable
    age int,
    -- string variable
    race varchar(255),
    -- string variable
    weapon varchar(255)
)
```

## Insert Rows Into Elf Table

```sql
INSERT INTO elves (name, age, race, weapon)
VALUES ('Dallar Woodfoot', 25, 'Elf', 'Bow'),
       ('Cordin Garner', 29, 'Elf', 'Bow'),
       ('Keat Knigh', 24, 'Elf', 'Sword'),
       ('Colbat Nalor', 124, 'Elf', 'Magic')
```

## Insert Rows Into Dwarf Table

```sql
INSERT INTO dwarves (name, age, race, weapon)
VALUES ('Kalog', 23, 'Dwarf', 'Axe'),
       ('Dranar', 145, 'Dwarf', 'Bow'),
       ('Bratar', 12, 'Dwarf', 'Axe'),
       ('Dragga', 23, 'Dwarf', 'Axe')
```

## Insert Rows Into Orc Table

```sql
INSERT INTO orcs (name, age, race, weapon)
VALUES ('Wokganit', 23, 'Orc', 'Sword'),
       ('Wudugog', 145, 'Orc', 'Axe'),
       ('Wegigoth', 12, 'Orc', 'Magic'),
       ('Wulgha', 23, 'Orc', 'Axe')
```

## Concatenate All Tables

```sql
-- All rows from elf table
SELECT * FROM elves
-- Concatenate with...
UNION ALL
-- All rows from dwarf table
SELECT * FROM dwarves
-- Concatenate with...
UNION ALL
-- All rows from orcs table
SELECT * FROM orcs
```
<table border="1" style="border-collapse:collapse">
<tr><th>name</th><th>age</th><th>race</th><th>weapon</th></tr>
<tr><td>Dallar Woodfoot</td><td>25</td><td>Elf</td><td>Bow</td></tr>
<tr><td>Cordin Garner</td><td>29</td><td>Elf</td><td>Bow</td></tr>
<tr><td>Keat Knigh</td><td>24</td><td>Elf</td><td>Sword</td></tr>
<tr><td>Colbat Nalor</td><td>124</td><td>Elf</td><td>Magic</td></tr>
<tr><td>Kalog</td><td>23</td><td>Dwarf</td><td>Axe</td></tr>
<tr><td>Dranar</td><td>145</td><td>Dwarf</td><td>Bow</td></tr>
<tr><td>Bratar</td><td>12</td><td>Dwarf</td><td>Axe</td></tr>
<tr><td>Dragga</td><td>23</td><td>Dwarf</td><td>Axe</td></tr>
<tr><td>Wokganit</td><td>23</td><td>Orc</td><td>Sword</td></tr>
<tr><td>Wudugog</td><td>145</td><td>Orc</td><td>Axe</td></tr>
<tr><td>Wegigoth</td><td>12</td><td>Orc</td><td>Magic</td></tr>
<tr><td>Wulgha</td><td>23</td><td>Orc</td><td>Axe</td></tr></table>