---
title: "Create Column Index"
description: "How to create column index in an SQL database."
tags: postgresql: basics
URL: https://github.com/ActiveState/code
Creator: 
Meta: 

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Create Column Index
        </h1>
        <p>How to create column index in an SQL database.</p>
    	</div>
		</div>

 <div style="height:40px">
<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
Example
</span>
</div>
</div>

## Create Table Of Elves

```sql
-- Create table called elves
CREATE TABLE elves (
    -- string variable
    name varchar(255),
    -- integer variable
    age int,
    -- string variable
    race varchar(255),
    -- string variable
    alive varchar(255)
)
```

## Insert Rows Into Elf Table

```sql
INSERT INTO elves (name, age, race, alive)
VALUES ('Dallar Woodfoot', 25, 'Elf', 'Yes'),
       ('Cordin Garner', 29, 'Elf', 'Yes'),
       ('Keat Knigh', 24, 'Elf', 'Yes'),
       ('Colbat Nalor', 124, 'Elf', 'Yes')
```

## Create Index

```sql
-- Index the names column in the elves table
CREATE INDEX ON elves (name)
```