---
title: "Transpose An Array"
description: "Using NumPy's transpose method to create a new view of a ndarray's data with the axes permuted in a given order."
tags: Numpy
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Transpose An Array
        </h1>
        <p>Using NumPy's transpose method to create a new view of a ndarray's data with the axes permuted in a given order.</p>
    	</div>
		</div>

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>

In [2]:
import numpy as np

In [ ]:
# by default, transpose() reverses depth (0), height (1), and width (2)
# this is equivalent to t.transpose((2, 1, 0))
new_arr = old_arr.transpose()

In [15]:
# transpose can take a tuple of integers as an argument
x = np.ones(((1,2,3)))
np.transpose(x, (1,0,2)).shape

(2, 1, 3)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>

## Let's create a 3D array:

In [125]:
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

## Now let's create an `ndarray` such that the axes `0, 1, 2` (depth, height, width) are re-ordered to `1, 2, 0`  
(depth → width, height → depth, width → height):

In [126]:
t1 = t.transpose((1,2,0))
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [127]:
t1.shape

(2, 3, 4)

## By default, `transpose` reverses the order of the dimensions:

In [128]:
t2 = t.transpose()
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [129]:
t2.shape

(3, 2, 4)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>

## NumPy provides a convenience function `swapaxes` to swap two axes.

For example, let's create a new view of `t` with depth and height swapped:

In [130]:
t3 = t.swapaxes(0,1)  # equivalent to t.transpose((1, 0, 2))
t3

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

In [131]:
t3.shape

(2, 4, 3)