In [27]:
import pandas as pd
import sqlite3
import os
import json
import sqlalchemy

In [28]:
class a_brick:
    __slots__ = ['_idNum', '_title','_desc','_code','_tags']
    
    def __init__ (self, idNum, title, desc, code, tags):
        self._idNum = idNum
        self._title = str(title)
        self._desc = str(desc)
        self._code = str(code)
        self._tags = str(tags)
    
    @property
    def idNum(self):
        return self._idNum
    
    @property
    def title(self):
        return self._title
    
    @property
    def desc(self):
        return self._desc
    
    @property
    def code(self):
        return self._code
    
    @property
    def tags(self):
        return self._tags
    
    @property
    def astuple(self):
        return (self.idNum, self.title, self.desc, self.code, self.tags)

In [29]:
rootdir = "../finalbricks/"
files = []
output = []

for filename in os.listdir(rootdir):
    if filename.endswith(".ipynb"): 
        files.append(filename)
    else:
        continue

#open each notebook in JSON format
for name in files:
    with open(rootdir+name) as json_file:
        code = json.load(json_file)
        nextfile = ()
        
        for item in code["cells"][0]["source"][1:4]: # we want title, description, and tags only
            item = item.replace('\"','').strip()
            index = item.find(':')
            nextfile += (item[index+2:],)
            
        title, desc, tags = nextfile
        # figure out how to fix the tags later
        brick = a_brick(None, title, desc, code, tags)
        output.append(brick.astuple)

In [30]:
sqlite_db = './bricks5.sqlite'
conn = sqlite3.connect(sqlite_db) 
c = conn.cursor()

In [32]:
for o in output:
    c.execute('INSERT INTO bricks5 VALUES (?, ?, ?, ?, ?)', o)

conn.commit()

In [34]:
df = pd.read_sql('SELECT * FROM bricks5 LIMIT 10', con=conn)
df

,id,title,desc,code,tags
0,1,Pandas select rows containing values,Pandas select rows containing values,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, EDA"
1,2,Pandas Crosstabs,using the crosstabs method pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing, EDA"
2,3,pandas select rows when the column has certain...,pandas select rows when the column has certain...,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, EDA"
3,4,Covert String to Float in Pandas,Changing the data type from string to float in...,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing, Text Pr..."
4,5,Converting Prices to Floats in Pandas,Turning a column of prices into floats in pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing, Regex, ..."
5,6,Pandas List the Unique Values in a Column,find the unique values in a column pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing"
6,7,Pandas Delete Duplicates,deleting and dropping duplicates pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing"
7,8,Pandas Find Unique Values,Finding unique values in a column pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, EDA"
8,9,Pandas Groupy Rows By,grouby in pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing"
9,10,Sum The Column of a DataFrame in Pandas,sum the column of a dataframe pandas,"{'cells': [{'cell_type': 'markdown', 'metadata...","Pandas, Data Cleaning / Preprocessing, EDA"