---
title: "Add Column to an Existing DataFrame Based off of Values in an Existing Column"
description: "Add a new column to an existing pandas dataframe. Use a Series, a list, or create a new column based off the values in an existing column."
tags: Pandas, Lists
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Add Column to an Existing DataFrame Based off of Values in an Existing Column
        </h1>
        <p>Add a new column to an existing pandas dataframe. Use a Series, a list, or create a new column based off the values in an existing column.</p>
    	</div>
		</div>

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>

In [ ]:
import pandas as pd

In [ ]:
# any operation will be performed element-wisef
df['new_column'] = df['old_column'] / 100

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>

## Create example DataFrame

In [76]:
people_dict = {
    "weight": [68, 83, 112],
    "birthyear": [1985, 1984, 1992],
    "children": [np.nan, 3, 0],
    "hobby": ["Biking", "Dancing", np.nan],
}
people = pd.DataFrame(people_dict, index=["alice", "bob", "charles"])
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

## New Column Based off of Existing column

In [77]:
people["age"] = 2019 - people["birthyear"]  # adds a new column "age"
people["over 30"] = people["age"] > 30      # adds another column "over 30"

people

         weight  birthyear  children    hobby  age  over 30
alice        68       1985       NaN   Biking   34     True
bob          83       1984       3.0  Dancing   35     True
charles     112       1992       0.0      NaN   27    False