---
title: "Sort a DataFrame by Index Label"
description: "Query the columns of a dataframe with a boolean expression and filter out the rows for which it holds true."
tags: Pandas
URL: https://github.com/ageron/handson-ml
Licence: Apache License 2.0
Creator: 
Meta: ""

---

 <div>
    	<img src="./coco.png" style="float: left;height: 55px">
    	<div style="height: 150px;text-align: center; padding-top:5px">
        <h1>
      	Sort a DataFrame by Index Label
        </h1>
        <p>Query the columns of a dataframe with a boolean expression and filter out the rows for which it holds true.</p>
    	</div>
		</div>

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Key Code
    	</span>
		</div>
		</div>

In [ ]:
import pandas as pd

By default the `sort_index` method sorts by index label and will return a sorted copy of the DataFrame. To modify the `df` directly, set the `inplace` argument to `True`.

In [ ]:
df.sort_index(inplace = True)

 <div style="height:40px">
		<div style="width:100%; text-align:center; border-bottom: 1px solid #000; line-height:0.1em; margin:40px 0 20px;">
    	<span style="background:#fff; padding:0 10px; font-size:25px; font-family: 'Open Sans', sans-serif;">
        Example
    	</span>
		</div>
		</div>

## Create example DataFrame

In [118]:
people_dict = {
    "weight": [68, 83, 112],
    "height": [172, 181, 185],
    "birthyear": [1985, 1984, 1992],
    "children": [np.nan, 3, 0],
    "hobby": ["Biking", "Dancing", np.nan],
}
people = pd.DataFrame(people_dict, index=["alice", "bob", "charles"])
people

         weight  height  birthyear  children    hobby
alice        68     172       1985       NaN   Biking
bob          83     181       1984       3.0  Dancing
charles     112     185       1992       0.0      NaN

### The rows are already sorted by their index label in ascending (lexicographical) order, so let's reverse the order.

In [119]:
people.sort_index(inplace = True, ascending = False)
people

         weight  height  birthyear  children    hobby
charles     112     185       1992       0.0      NaN
bob          83     181       1984       3.0  Dancing
alice        68     172       1985       NaN   Biking